What is numpy?

NumPy (short for "Numerical Python") is one of the most fundamental packages for scientific computations in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Installation:

To install numpy, we can use pip:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Creating an array:

NumPy's main object is the homogeneous multidimensional array. 

In [2]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


Basic Operations:

Operations in NumPy can be element-wise

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) 

[5 7 9]


1-D Array:

In [9]:
array_1d = np.array([1, 2, 3, 4])


2D Array

In [10]:
array_2d = np.array([[1, 2], [3, 4]])


3D Array

In [11]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Array attributes:

Check the shape, dimensions, data type, and size of an array:

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)


Shape: (2, 3)
Dimensions: 2
Data Type: int32
Size: 6


Mathematical Operations:

Addition, subtraction, multiplication, division

In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])


print(x + y)

print(x - y)

print(x * y)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


Array creation is one of the fundamental tasks in NumPy. You can create arrays from lists, tuples, or use specialized functions provided by NumPy to generate arrays of zeros, ones, sequences, and random values, among others

Lists and Tuples:

In [15]:
import numpy as np

arr_from_list = np.array([1, 2, 3, 4])
print(arr_from_list)

arr_from_tuple = np.array((5, 6, 7, 8))
print(arr_from_tuple)


[1 2 3 4]
[5 6 7 8]


Using Zeros, Ones, and Full:

In [16]:

zeros_arr = np.zeros((2, 3))
print(zeros_arr)

ones_arr = np.ones((2, 3))
print(ones_arr)

full_arr = np.full((2, 3), 7)
print(full_arr)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


Indexing in NumPy arrays (often referred to as ndarray, which stands for N-dimensional array) allows you to access and modify specific elements, rows, columns, or sections of the array. Let's go over some essential indexing techniques:


For 1D arrays, it works similarly to standard Python lists:

In [18]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[2])  


3


2D arrays

In [19]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2]) 


6


What is slicing 

1D array slicing:

In [20]:
print(arr_1d[1:4])  


[2 3 4]


2D array slicing

In [21]:
print(arr_2d[0:2, 1:3])  


[[2 3]
 [5 6]]


object: Python objects.

datetime64: Date and time values.

timedelta64: Differences between two dates/times.

dtype

In [22]:
import numpy as np

arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)


In [23]:
print(arr_int.dtype)  


int32


Broadcasting in NumPy refers to the set of rules that allows operations to be performed on arrays of different shapes and sizes. It's a powerful feature that lets you perform element-wise operations without necessarily having matching dimensions between arrays.


Broadcasting automates certain operations to make arrays compatible for arithmetic operations. For instance, adding a scalar to an array or adding arrays of different but compatible dimensions.

Examples:

Scalar Broadcasting:

In [24]:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + 5 
print(result)  


[6 7 8]


In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2  
print(result)  


[[2 4 6]
 [5 7 9]]


In NumPy, understanding the distinction between copies and views is crucial, especially when modifying data in arrays. Mistaking one for the other can lead to unintended data modifications.

In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr[1:4]
view_arr[1] = 10
print(arr)  


[ 1  2 10  4  5]


Checking

In [27]:
print(view_arr.base)  


[ 1  2 10  4  5]


Creation: Use the copy() method to explicitly create a copy.

In [28]:
arr_copy = arr.copy()


Modification:

In [29]:
arr_copy[2] = 20
print(arr)      
print(arr_copy) 


[ 1  2 10  4  5]
[ 1  2 20  4  5]


Structured arrays (or record arrays) in NumPy allow you to define arrays with fields (similar to columns in a table), where each field can have a unique data type. This makes them useful for heterogeneous data sets.

Creating Structured Arrays:

Using a List of Tuples:

Each tuple consists of a field name and its data type.

In [31]:
import numpy as np

dt = [('name', 'U10'), ('age', 'i4'), ('height', 'f8')]
people = np.array([('ali', 25, 5.5), ('wali', 30, 6.2), ('shaheer', 35, 5.8)], dtype=dt)


In [32]:
dt = {'names': ('name', 'age', 'height'), 'formats': ('U10', 'i4', 'f8')}
people = np.array([('ali', 25, 5.5), ('wali', 30, 6.2), ('shaheer', 35, 5.8)], dtype=dt)


Accessing Data:

In [33]:
print(people['name'])  

['ali' 'wali' 'shaheer']
